/*
 * File: app/view/pnAddListMoneyWindows.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.pnAddListMoneyWindows', {
    extend: 'Ext.window.Window',
    alias: 'widget.pnAddListMoneyWindows',

    draggable: false,
    height: 401,
    width: 685,
    resizable: //true
false,
    layout: {
        type: 'border'
    },
    title: 'เพิ่มข้อมูลรับเงิน',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    id: 'pnAddListMoney',
                    items: [
                        {
                            xtype: 'fieldset',
                            margin: '10 10 10 10',
                            padding: 10,
                            title: '',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    id: 'id',
                                    errorMsgCls: 'poooooopppppppppppppppppppppppoplp',
                                    fieldLabel: 'รหัส',
                                    msgTarget: 'title',
                                    name: 'id',
                                    emptyText: 'รหัสข้อมูล',
                                    hideTrigger: true,
                                    listeners: {
                                        afterrender: {
                                            fn: me.onIdAfterRender,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'datefield',
                                    id: 'date',
                                    fieldLabel: 'วันที่โอน',
                                    msgTarget: 'side',
                                    name: 'date',
                                    emptyText: '',
                                    editable: false
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'transaction',
                                    fieldLabel: 'ประเภทรายการ',
                                    name: 'transaction',
                                    editable: false,
                                    displayField: 'Type',
                                    store: 'depositType'
                                },
                                {
                                    xtype: 'numberfield',
                                    formBind: false,
                                    id: 'deposit',
                                    fieldLabel: 'ยอดเงิน',
                                    msgTarget: 'side',
                                    name: 'deposit',
                                    allowBlank: false,
                                    emptyText: 'จำนวนที่เงิน',
                                    regexText: 'โปรดใส่ข้อมูล จำนวนเงินที่ถอน',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'textfield',
                                    getTip: function() {
                                        var tip = this.tip;
                                        if (!tip) {
                                            tip = this.tip = Ext.widget('tooltip', {
                                                target: this.el,
                                                title: 'Error Details:',
                                                autoHide: false,
                                                anchor: 'top',
                                                mouseOffset: [-11, -2],
                                                closable: true,
                                                constrainPosition: false,
                                                cls: 'errors-tip'
                                            });
                                            tip.show();
                                        }
                                        return tip;
                                    },
                                    id: 'tellerId',
                                    afterLabelTextTpl: [
                                        '<span style="color:red;font-weight:100px" data-qtip="Required">*</span>'
                                    ],
                                    fieldLabel: 'หมายเลขกำกับ',
                                    msgTarget: 'side',
                                    name: 'tellerId',
                                    emptyText: ''
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            id: 'btnSave',
                            itemId: 'btnSave',
                            margin: '0 0 0 10',
                            width: 100,
                            text: 'บันทึก'
                        },
                        {
                            xtype: 'button',
                            id: 'btnEdit',
                            margin: '0 0 0 10',
                            width: 100,
                            text: 'แก้ไขข้อมูล'
                        },
                        {
                            xtype: 'button',
                            id: 'btnClear',
                            margin: '0 0 0 10',
                            width: 100,
                            text: 'ล้างข้อมูล'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    margins: ' 0 0 0 10',
                    region: 'north',
                    height: 83,
                    id: 'pnBankForm',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'bookBanks',
                            margin: '0 0 0 10',
                            width: 254,
                            fieldLabel: 'ชื่อธนาคาร',
                            name: 'bookBank',
                            displayField: 'bookBank',
                            store: 'BankAccountStore'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'accountNumber',
                            margin: '10 0 0 10',
                            fieldLabel: 'เลขที่บัญชี:',
                            name: 'accountNumber'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onIdAfterRender: function(component, eOpts) {

        var view = Ext.create('MyApp.view.pnAddListMoneyWindows');
        var tip = Ext.create('Ext.tip.ToolTip', {
            // The overall target element.
            target: view.el,
            // Each grid row causes its own separate show and hide.
            delegate: view.itemSelector,
            // Moving within the row should not hide the tip.
            trackMouse: true,
            // Render immediately so that tip.body can be referenced prior to the first show.
            renderTo: Ext.getBody(),
            listeners: {
                // Change content dynamically depending on which element triggered the show.
                beforeshow: function updateTipBody(tip) {
                    tip.update('Over company "' + view.getRecord(tip.triggerElement).get('company') + '"');
                }
            }
        });
        //});


        console.log('kkkkkkkkkkk');
    }

});